import { College } from './types';

export const colleges: College[] = [
  {
    id: 1,
    name: 'Andhra University College of Engineering',
    city: 'Visakhapatnam',
    district: 'Visakhapatnam',
    description:
      'A premier institution for engineering education in Andhra Pradesh, known for its strong faculty and research facilities. It has a sprawling campus with a vibrant student life.',
    courses: [
      { id: 'cse', name: 'Computer Science and Engineering', department: 'Engineering' },
      { id: 'ece', name: 'Electronics and Communication Engineering', department: 'Engineering' },
      { id: 'mech', name: 'Mechanical Engineering', department: 'Engineering' },
      { id: 'civil', name: 'Civil Engineering', department: 'Engineering' },
    ],
    facilities: ['Library', 'Wi-Fi Campus', 'Sports Complex', 'Auditorium', 'Labs', 'Cafeteria'],
    hostelInfo: 'Separate hostels for boys and girls with mess facilities. Capacity of 2000+ students.',
    admissionCutoff: 'Based on AP EAMCET rank. Top 5000 rank required for CSE.',
    rating: 4.5,
    reviews: [
      { id: 1, author: 'Ravi Kumar', rating: 5, comment: 'Excellent faculty and campus life. Placements are great for CSE.', date: '2023-05-10' },
      { id: 2, author: 'Priya Sharma', rating: 4, comment: 'Good infrastructure, but the hostel food could be better.', date: '2023-04-22' },
      { id: 3, author: 'Anil Varma', rating: 5, comment: 'One of the best colleges in the state. The peer group is amazing.', date: '2023-08-01' },
    ],
    images: ['college-campus-1', 'college-campus-2', 'college-campus-5'],
    logoUrl: 'college-logo-1',
    location: { lat: 17.729, lng: 83.322 },
    mapImage: 'map-placeholder-1',
  },
  {
    id: 2,
    name: 'Gitam University, Vizag',
    city: 'Visakhapatnam',
    district: 'Visakhapatnam',
    description:
      'A leading private university with a focus on technology and management. It offers a wide range of undergraduate and postgraduate programs.',
    courses: [
      { id: 'cse', name: 'Computer Science and Engineering', department: 'Engineering' },
      { id: 'it', name: 'Information Technology', department: 'Engineering' },
      { id: 'bba', name: 'Bachelor of Business Administration', department: 'Management' },
      { id: 'bcom', name: 'Bachelor of Commerce', department: 'Commerce' },
      { id: 'biotech', name: 'Biotechnology', department: 'Science' },
    ],
    facilities: ['Modern Library', 'AC Classrooms', 'Swimming Pool', 'Gym', 'Cafeteria', 'Incubation Center'],
    hostelInfo: 'Well-maintained hostels with single and double occupancy rooms available.',
    admissionCutoff: 'Admission through GAT (GITAM Admission Test).',
    rating: 4.2,
    reviews: [
      { id: 1, author: 'Arjun Reddy', rating: 4, comment: 'Great campus and facilities. The curriculum is very modern.', date: '2023-06-15' },
      { id: 2, author: 'Sneha Rao', rating: 5, comment: 'I loved my time at GITAM. The faculty is very supportive.', date: '2023-03-18' },
    ],
    images: ['college-campus-3', 'college-campus-4'],
    logoUrl: 'college-logo-2',
    location: { lat: 17.781, lng: 83.379 },
    mapImage: 'map-placeholder-2',
  },
  {
    id: 3,
    name: 'Sri Venkateswara University College of Engineering',
    city: 'Tirupati',
    district: 'Chittoor',
    description:
      'Established in 1959, SVUCE is one of the oldest and most respected engineering colleges in the state. It is located in the temple town of Tirupati.',
    courses: [
      { id: 'cse', name: 'Computer Science and Engineering', department: 'Engineering' },
      { id: 'eee', name: 'Electrical and Electronics Engineering', department: 'Engineering' },
      { id: 'mech', name: 'Mechanical Engineering', department: 'Engineering' },
      { id: 'bsc', name: 'Bachelor of Science (Physics)', department: 'Science' },
    ],
    facilities: ['Central Library', 'Computer Center', 'Workshops', 'Medical Center', 'NSS'],
    hostelInfo: 'Comprehensive hostel facilities for all students.',
    admissionCutoff: 'Admission through AP EAMCET rank.',
    rating: 4.3,
    reviews: [
      { id: 1, author: 'Karthik N', rating: 4, comment: 'Good college with a lot of history. Faculty is experienced.', date: '2023-02-01' },
      { id: 2, author: 'Lakshmi P', rating: 5, comment: 'Peaceful campus environment. Good for focused studies.', date: '2023-01-25' },
    ],
    images: ['college-campus-1', 'college-campus-4', 'college-campus-5'],
    logoUrl: 'college-logo-3',
    location: { lat: 13.633, lng: 79.419 },
    mapImage: 'map-placeholder-3',
  },
  {
    id: 4,
    name: 'JNTU College of Engineering, Kakinada',
    city: 'Kakinada',
    district: 'East Godavari',
    description: 'A prestigious technical university, JNTUK is renowned for its academic excellence and research contributions in engineering and technology.',
    courses: [
        { id: 'cse', name: 'Computer Science and Engineering', department: 'Engineering' },
        { id: 'it', name: 'Information Technology', department: 'Engineering' },
        { id: 'petro', name: 'Petroleum Engineering', department: 'Engineering' },
        { id: 'ece', name: 'Electronics and Communication Engineering', department: 'Engineering' },
    ],
    facilities: ['Digital Library', 'Research Labs', 'Hostel', 'Sports Ground', 'Transport'],
    hostelInfo: 'Hostels available for both boys and girls with all necessary amenities.',
    admissionCutoff: 'AP EAMCET top ranks preferred. Highly competitive.',
    rating: 4.6,
    reviews: [
        { id: 1, author: 'Suresh Babu', rating: 5, comment: 'Top-notch education. The petroleum engineering department is one of the best.', date: '2023-07-20' },
        { id: 2, author: 'Divya Chowdary', rating: 4, comment: 'Strict academics, but it prepares you well for the industry.', date: '2023-09-11' },
    ],
    images: ['college-campus-2', 'college-campus-3'],
    logoUrl: 'college-logo-1',
    location: { lat: 16.99, lng: 82.25 },
    mapImage: 'map-placeholder-1',
  },
  {
    id: 5,
    name: 'KL University',
    city: 'Vaddeswaram',
    district: 'Guntur',
    description: 'Koneru Lakshmaiah Education Foundation is a deemed university known for its modern infrastructure, industry-oriented curriculum, and emphasis on innovation.',
    courses: [
        { id: 'cse', name: 'Computer Science and Engineering', department: 'Engineering' },
        { id: 'robotics', name: 'Robotics and Automation', department: 'Engineering' },
        { id: 'mba', name: 'Master of Business Administration', department: 'Management' },
        { id: 'law', name: 'Bachelor of Laws (LLB)', department: 'Law' },
    ],
    facilities: ['Innovation Garage', 'E-Learning Center', 'Food Courts', 'Indoor Stadium', 'Bank'],
    hostelInfo: 'AC and Non-AC hostel rooms with various sharing options.',
    admissionCutoff: 'Based on KLEEE (KL Engineering Entrance Exam) or other national level exams.',
    rating: 4.4,
    reviews: [
        { id: 1, author: 'Rahul Varma', rating: 5, comment: 'Amazing campus with endless opportunities to learn and grow.', date: '2023-08-05' },
        { id: 2, author: 'Aishwarya J', rating: 4, comment: 'Good placement support, but the fee is on the higher side.', date: '2023-07-30' },
    ],
    images: ['college-campus-4', 'college-campus-1'],
    logoUrl: 'college-logo-2',
    location: { lat: 16.44, lng: 80.62 },
    mapImage: 'map-placeholder-2',
  },
  {
    id: 6,
    name: 'SRM University, AP',
    city: 'Amaravati',
    district: 'Guntur',
    description: 'A multi-stream research university with a focus on interdisciplinary learning and global exposure. It boasts a world-class campus designed by Perkins+Will.',
    courses: [
        { id: 'cse-ai', name: 'CSE (AI & Machine Learning)', department: 'Engineering' },
        { id: 'env', name: 'Environmental Science', department: 'Science' },
        { id: 'liberal-arts', name: 'Liberal Arts & Basic Sciences', department: 'Humanities' },
        { id: 'ba', name: 'Bachelor of Arts', department: 'Humanities' },
    ],
    facilities: ['Next-Gen Labs', 'Hostel with integrated amenities', 'Learning and Innovation Hub', 'Sports fields', 'Health Center'],
    hostelInfo: 'State-of-the-art hostel facilities with an emphasis on student well-being.',
    admissionCutoff: 'Admission through SRMJEEE (SRM Joint Engineering Entrance Examination).',
    rating: 4.1,
    reviews: [
        { id: 1, author: 'Pooja Hegde', rating: 4, comment: 'The infrastructure is futuristic. Faculty are from reputed institutions.', date: '2024-01-10' },
        { id: 2, author: 'Naveen P', rating: 4, comment: 'Still a new university but has a lot of potential. Research opportunities are good.', date: '2023-11-22' },
    ],
    images: ['college-campus-5', 'college-campus-2'],
    logoUrl: 'college-logo-3',
    location: { lat: 16.54, lng: 80.52 },
    mapImage: 'map-placeholder-3',
  }
];

export const allCourses = Array.from(new Set(colleges.flatMap(c => c.courses.map(course => course.department)))).sort();
export const allDistricts = Array.from(new Set(colleges.map(c => c.district))).sort();
