import { College } from './types';

export const colleges: College[] = [
  {
    id: 1,
    name: 'Andhra University College of Engineering',
    city: 'Visakhapatnam',
    district: 'Visakhapatnam',
    description:
      'A premier institution for engineering education in Andhra Pradesh, known for its strong faculty and research facilities. It has a sprawling campus with a vibrant student life.',
    courses: [
      { id: 'cse', name: 'Computer Science and Engineering', department: 'Engineering' },
      { id: 'ece', name: 'Electronics and Communication Engineering', department: 'Engineering' },
      { id: 'mech', name: 'Mechanical Engineering', department: 'Engineering' },
      { id: 'civil', name: 'Civil Engineering', department: 'Engineering' },
    ],
    facilities: ['Library', 'Wi-Fi Campus', 'Sports Complex', 'Auditorium', 'Labs', 'Cafeteria'],
    hostelInfo: 'Separate hostels for boys and girls with mess facilities. Capacity of 2000+ students.',
    admissionCutoff: 'Based on AP EAMCET rank. Top 5000 rank required for CSE.',
    rating: 4.5,
    reviews: [
      { id: 1, author: 'Ravi Kumar', rating: 5, comment: 'Excellent faculty and campus life. Placements are great for CSE.', date: '2023-05-10' },
      { id: 2, author: 'Priya Sharma', rating: 4, comment: 'Good infrastructure, but the hostel food could be better.', date: '2023-04-22' },
      { id: 3, author: 'Anil Varma', rating: 5, comment: 'One of the best colleges in the state. The peer group is amazing.', date: '2023-08-01' },
    ],
    images: ['college-campus-1', 'college-campus-2', 'college-campus-5'],
    logoUrl: 'college-logo-1',
    location: { lat: 17.729, lng: 83.322 },
    mapImage: 'map-placeholder-1',
  },
  {
    id: 2,
    name: 'GITAM (Gandhi Institute of Technology and Management)',
    city: 'Visakhapatnam',
    district: 'Visakhapatnam',
    description:
      'A leading private university with a focus on technology and management. It offers a wide range of undergraduate and postgraduate programs.',
    courses: [
      { id: 'cse', name: 'Computer Science and Engineering', department: 'Engineering' },
      { id: 'it', name: 'Information Technology', department: 'Engineering' },
      { id: 'bba', name: 'Bachelor of Business Administration', department: 'Management' },
      { id: 'bcom', name: 'Bachelor of Commerce', department: 'Commerce' },
      { id: 'biotech', name: 'Biotechnology', department: 'Science' },
    ],
    facilities: ['Modern Library', 'AC Classrooms', 'Swimming Pool', 'Gym', 'Cafeteria', 'Incubation Center'],
    hostelInfo: 'Well-maintained hostels with single and double occupancy rooms available.',
    admissionCutoff: 'Admission through GAT (GITAM Admission Test).',
    rating: 4.2,
    reviews: [
      { id: 1, author: 'Arjun Reddy', rating: 4, comment: 'Great campus and facilities. The curriculum is very modern.', date: '2023-06-15' },
      { id: 2, author: 'Sneha Rao', rating: 5, comment: 'I loved my time at GITAM. The faculty is very supportive.', date: '2023-03-18' },
    ],
    images: ['college-campus-3', 'college-campus-4'],
    logoUrl: 'college-logo-2',
    location: { lat: 17.781, lng: 83.379 },
    mapImage: 'map-placeholder-2',
  },
  {
    id: 3,
    name: 'Sri Venkateswara University College of Engineering',
    city: 'Tirupati',
    district: 'Tirupati',
    description:
      'Established in 1959, SVUCE is one of the oldest and most respected engineering colleges in the state. It is located in the temple town of Tirupati.',
    courses: [
      { id: 'cse', name: 'Computer Science and Engineering', department: 'Engineering' },
      { id: 'eee', name: 'Electrical and Electronics Engineering', department: 'Engineering' },
      { id: 'mech', name: 'Mechanical Engineering', department: 'Engineering' },
      { id: 'bsc', name: 'Bachelor of Science (Physics)', department: 'Science' },
    ],
    facilities: ['Central Library', 'Computer Center', 'Workshops', 'Medical Center', 'NSS'],
    hostelInfo: 'Comprehensive hostel facilities for all students.',
    admissionCutoff: 'Admission through AP EAMCET rank.',
    rating: 4.3,
    reviews: [
      { id: 1, author: 'Karthik N', rating: 4, comment: 'Good college with a lot of history. Faculty is experienced.', date: '2023-02-01' },
      { id: 2, author: 'Lakshmi P', rating: 5, comment: 'Peaceful campus environment. Good for focused studies.', date: '2023-01-25' },
    ],
    images: ['college-campus-1', 'college-campus-4', 'college-campus-5'],
    logoUrl: 'college-logo-3',
    location: { lat: 13.6288, lng: 79.4192 },
    mapImage: 'map-placeholder-3',
  },
  {
    id: 4,
    name: 'JNTU College of Engineering, Kakinada',
    city: 'Kakinada',
    district: 'Kakinada',
    description: 'A prestigious technical university, JNTUK is renowned for its academic excellence and research contributions in engineering and technology.',
    courses: [
        { id: 'cse', name: 'Computer Science and Engineering', department: 'Engineering' },
        { id: 'it', name: 'Information Technology', department: 'Engineering' },
        { id: 'petro', name: 'Petroleum Engineering', department: 'Engineering' },
        { id: 'ece', name: 'Electronics and Communication Engineering', department: 'Engineering' },
    ],
    facilities: ['Digital Library', 'Research Labs', 'Hostel', 'Sports Ground', 'Transport'],
    hostelInfo: 'Hostels available for both boys and girls with all necessary amenities.',
    admissionCutoff: 'AP EAMCET top ranks preferred. Highly competitive.',
    rating: 4.6,
    reviews: [
        { id: 1, author: 'Suresh Babu', rating: 5, comment: 'Top-notch education. The petroleum engineering department is one of the best.', date: '2023-07-20' },
        { id: 2, author: 'Divya Chowdary', rating: 4, comment: 'Strict academics, but it prepares you well for the industry.', date: '2023-09-11' },
    ],
    images: ['college-campus-2', 'college-campus-3'],
    logoUrl: 'college-logo-1',
    location: { lat: 16.99, lng: 82.25 },
    mapImage: 'map-placeholder-1',
  },
  {
    id: 5,
    name: 'KL University',
    city: 'Vaddeswaram',
    district: 'Guntur',
    description: 'Koneru Lakshmaiah Education Foundation is a deemed university known for its modern infrastructure, industry-oriented curriculum, and emphasis on innovation.',
    courses: [
        { id: 'cse', name: 'Computer Science and Engineering', department: 'Engineering' },
        { id: 'robotics', name: 'Robotics and Automation', department: 'Engineering' },
        { id: 'mba', name: 'Master of Business Administration', department: 'Management' },
        { id: 'law', name: 'Bachelor of Laws (LLB)', department: 'Law' },
    ],
    facilities: ['Innovation Garage', 'E-Learning Center', 'Food Courts', 'Indoor Stadium', 'Bank'],
    hostelInfo: 'AC and Non-AC hostel rooms with various sharing options.',
    admissionCutoff: 'Based on KLEEE (KL Engineering Entrance Exam) or other national level exams.',
    rating: 4.4,
    reviews: [
        { id: 1, author: 'Rahul Varma', rating: 5, comment: 'Amazing campus with endless opportunities to learn and grow.', date: '2023-08-05' },
        { id: 2, author: 'Aishwarya J', rating: 4, comment: 'Good placement support, but the fee is on the higher side.', date: '2023-07-30' },
    ],
    images: ['college-campus-4', 'college-campus-1'],
    logoUrl: 'college-logo-2',
    location: { lat: 16.4418, lng: 80.6228 },
    mapImage: 'map-placeholder-2',
  },
  {
    id: 6,
    name: 'SRM University, AP',
    city: 'Amaravati',
    district: 'Guntur',
    description: 'A multi-stream research university with a focus on interdisciplinary learning and global exposure. It boasts a world-class campus designed by Perkins+Will.',
    courses: [
        { id: 'cse-ai', name: 'CSE (AI & Machine Learning)', department: 'Engineering' },
        { id: 'env', name: 'Environmental Science', department: 'Science' },
        { id: 'liberal-arts', name: 'Liberal Arts & Basic Sciences', department: 'Humanities' },
        { id: 'ba', name: 'Bachelor of Arts', department: 'Humanities' },
    ],
    facilities: ['Next-Gen Labs', 'Hostel with integrated amenities', 'Learning and Innovation Hub', 'Sports fields', 'Health Center'],
    hostelInfo: 'State-of-the-art hostel facilities with an emphasis on student well-being.',
    admissionCutoff: 'Admission through SRMJEEE (SRM Joint Engineering Entrance Examination).',
    rating: 4.1,
    reviews: [
        { id: 1, author: 'Pooja Hegde', rating: 4, comment: 'The infrastructure is futuristic. Faculty are from reputed institutions.', date: '2024-01-10' },
        { id: 2, author: 'Naveen P', rating: 4, comment: 'Still a new university but has a lot of potential. Research opportunities are good.', date: '2023-11-22' },
    ],
    images: ['college-campus-5', 'college-campus-2'],
    logoUrl: 'college-logo-3',
    location: { lat: 16.5445, lng: 80.5218 },
    mapImage: 'map-placeholder-3',
  },
  {
    id: 7,
    name: 'Vignan\'s Foundation for Science, Technology & Research',
    city: 'Vadlamudi',
    district: 'Guntur',
    description: 'A deemed university offering a wide array of courses. It has a strong focus on research and has collaborations with various industries.',
    courses: [
        { id: 'cse', name: 'Computer Science and Engineering', department: 'Engineering' },
        { id: 'agri', name: 'Agricultural Engineering', department: 'Engineering' },
        { id: 'pharma', name: 'Pharmacy', department: 'Pharmacy' },
        { id: 'mca', name: 'Master of Computer Applications', department: 'Computer Applications' },
    ],
    facilities: ['Central Library', 'Digital Library', 'Auditorium', 'Sports Complex', 'Gym'],
    hostelInfo: 'Separate hostels for boys and girls with good security and facilities.',
    admissionCutoff: 'Admission through V-SAT (Vignan Scholastic Aptitude Test).',
    rating: 4.3,
    reviews: [
        { id: 1, author: 'Sita Ram', rating: 4, comment: 'Good focus on practical knowledge. The labs are well-equipped.', date: '2023-10-15' },
        { id: 2, author: 'Geetha M', rating: 5, comment: 'Vibrant campus life with lots of events and clubs.', date: '2023-09-02' },
    ],
    images: ['college-campus-1', 'college-campus-3'],
    logoUrl: 'college-logo-1',
    location: { lat: 16.353, lng: 80.551 },
    mapImage: 'map-placeholder-1',
  },
  {
    id: 8,
    name: 'Gayatri Vidya Parishad College of Engineering',
    city: 'Visakhapatnam',
    district: 'Visakhapatnam',
    description: 'An autonomous college affiliated to JNTUK, known for its academic discipline and experienced faculty. It has consistently high placement records.',
    courses: [
        { id: 'cse', name: 'Computer Science and Engineering', department: 'Engineering' },
        { id: 'chem', name: 'Chemical Engineering', department: 'Engineering' },
        { id: 'ece', name: 'Electronics and Communication Engineering', department: 'Engineering' },
    ],
    facilities: ['Library', 'Wi-Fi', 'Labs', 'Cafeteria', 'Sports', 'Transport'],
    hostelInfo: 'Limited hostel facility available inside the campus.',
    admissionCutoff: 'Requires a good rank in AP EAMCET.',
    rating: 4.4,
    reviews: [
        { id: 1, author: 'Rajesh Kumar', rating: 5, comment: 'One of the best engineering colleges in Vizag. Placements are assured for CSE.', date: '2023-04-12' },
    ],
    images: ['college-campus-2', 'college-campus-5'],
    logoUrl: 'college-logo-2',
    location: { lat: 17.742, lng: 83.333 },
    mapImage: 'map-placeholder-2',
  },
  {
    id: 9,
    name: 'RVR & JC College of Engineering',
    city: 'Guntur',
    district: 'Guntur',
    description: 'A well-established autonomous engineering college, known for its strong alumni network and consistent academic performance.',
    courses: [
        { id: 'cse', name: 'Computer Science and Engineering', department: 'Engineering' },
        { id: 'it', name: 'Information Technology', department: 'Engineering' },
        { id: 'mech', 'name': 'Mechanical Engineering', department: 'Engineering' },
    ],
    facilities: ['Library', 'Computer Center', 'Sports', 'Hostel', 'Gym'],
    hostelInfo: 'Good hostel facilities with a disciplined environment.',
    admissionCutoff: 'AP EAMCET rank is the primary criteria.',
    rating: 4.2,
    reviews: [
        { id: 1, author: 'Murali Krishna', rating: 4, comment: 'A reputed college in Guntur. The civil and mechanical departments are very strong.', date: '2023-05-25' },
    ],
    images: ['college-campus-4', 'college-campus-1'],
    logoUrl: 'college-logo-3',
    location: { lat: 16.333, lng: 80.358 },
    mapImage: 'map-placeholder-3',
  },
  {
    id: 10,
    name: 'Sree Vidyanikethan Engineering College',
    city: 'Tirupati',
    district: 'Tirupati',
    description: 'Founded by actor Dr. M. Mohan Babu, this college is known for its discipline, infrastructure, and quality education.',
    courses: [
        { id: 'cse', name: 'Computer Science and Engineering', department: 'Engineering' },
        { id: 'ece', name: 'Electronics and Communication Engineering', department: 'Engineering' },
        { id: 'eee', name: 'Electrical and Electronics Engineering', department: 'Engineering' },
    ],
    facilities: ['World-class infrastructure', 'Central Library', 'Auditorium', 'Hostels', 'Canteen'],
    hostelInfo: 'Excellent hostel facilities often praised by students and parents.',
    admissionCutoff: 'Admissions through AP EAMCET and management quota.',
    rating: 4.3,
    reviews: [
        { id: 1, author: 'Deepika S', rating: 5, comment: 'Beautiful campus and great learning environment. Placements are really good.', date: '2023-08-19' },
    ],
    images: ['college-campus-3', 'college-campus-5'],
    logoUrl: 'college-logo-1',
    location: { lat: 13.628, lng: 79.333 },
    mapImage: 'map-placeholder-1',
  },
  {
    id: 11,
    name: 'Andhra Loyola College',
    city: 'Vijayawada',
    district: 'NTR',
    description: 'An autonomous college with a rich history, known for its excellence in arts and sciences. It has been conferred "College of Excellence" status by UGC.',
    courses: [
        { id: 'bsc', name: 'B.Sc. (Maths, Physics, Chemistry)', department: 'Science' },
        { id: 'ba', name: 'B.A. (History, Economics, Politics)', department: 'Humanities' },
        { id: 'bcom', name: 'B.Com (Computers)', department: 'Commerce' },
    ],
    facilities: ['Historic Library', 'Auditorium', 'Sports Grounds', 'Canteen', 'Chapel'],
    hostelInfo: 'Hostel facilities are available for male students.',
    admissionCutoff: 'Based on merit in the qualifying examination.',
    rating: 4.7,
    reviews: [
        { id: 1, author: 'John Doe', rating: 5, comment: 'One of the best degree colleges in AP. The discipline and quality of education are unparalleled.', date: '2023-03-03' },
    ],
    images: ['college-campus-1', 'college-campus-2'],
    logoUrl: 'college-logo-2',
    location: { lat: 16.518, lng: 80.643 },
    mapImage: 'map-placeholder-2',
  },
  {
    id: 12,
    name: 'P.B. Siddhartha College of Arts & Science',
    city: 'Vijayawada',
    district: 'NTR',
    description: 'A well-regarded autonomous college in Vijayawada offering a variety of undergraduate and postgraduate courses.',
    courses: [
        { id: 'mba', name: 'Master of Business Administration', department: 'Management' },
        { id: 'mca', name: 'Master of Computer Applications', department: 'Computer Applications' },
        { id: 'bsc-cs', name: 'B.Sc. (Computer Science)', department: 'Science' },
    ],
    facilities: ['Library', 'Computer Labs', 'Seminar Hall', 'Sports Facilities'],
    hostelInfo: 'Hostel facility is available for students.',
    admissionCutoff: 'Based on merit and entrance tests like AP ICET for PG courses.',
    rating: 4.1,
    reviews: [
      { id: 1, author: 'Varun Tej', rating: 4, comment: 'Good college for PG courses like MCA and MBA. Decent placements.', date: '2023-07-07' },
    ],
    images: ['college-campus-4', 'college-campus-3'],
    logoUrl: 'college-logo-3',
    location: { lat: 16.510, lng: 80.655 },
    mapImage: 'map-placeholder-3',
  },
  {
    id: 13,
    name: 'Government College (Autonomous), Rajahmundry',
    city: 'Rajahmundry',
    district: 'East Godavari',
    description: 'A historic and autonomous government college, it has been a center for learning in the Godavari districts for over 150 years.',
    courses: [
        { id: 'ba', name: 'Bachelor of Arts', department: 'Humanities' },
        { id: 'bcom', name: 'Bachelor of Commerce', department: 'Commerce' },
        { id: 'bsc', name: 'Bachelor of Science', department: 'Science' },
    ],
    facilities: ['Vast Library', 'Historic Buildings', 'Sports Ground', 'Auditorium'],
    hostelInfo: 'Basic hostel facilities are provided for students from remote areas.',
    admissionCutoff: 'Merit-based admission for undergraduate courses.',
    rating: 4.0,
    reviews: [
      { id: 1, author: 'K. Sastry', rating: 4, comment: 'A college with great legacy and experienced lecturers. Campus is huge.', date: '2022-12-10' },
    ],
    images: ['college-campus-5', 'college-campus-1'],
    logoUrl: 'college-logo-1',
    location: { lat: 17.001, lng: 81.792 },
    mapImage: 'map-placeholder-1',
  },
   {
    id: 14,
    name: 'Aditya Engineering College',
    city: 'Surampalem',
    district: 'Kakinada',
    description: 'Part of the Aditya Educational Institutions, this college is known for its large campus and wide range of engineering disciplines.',
    courses: [
        { id: 'cse', name: 'Computer Science and Engineering', department: 'Engineering' },
        { id: 'agri', name: 'Agricultural Engineering', department: 'Engineering' },
        { id: 'mining', name: 'Mining Engineering', department: 'Engineering' },
    ],
    facilities: ['Technology Business Incubator', 'Central Library', 'AC Hostels', 'Transport', 'Food Court'],
    hostelInfo: 'Separate AC and Non-AC hostels for boys and girls.',
    admissionCutoff: 'Admission through AP EAMCET.',
    rating: 4.0,
    reviews: [
        { id: 1, author: 'Santosh Kumar', rating: 4, comment: 'Good infrastructure and a lot of encouragement for extracurricular activities.', date: '2023-01-20' },
    ],
    images: ['college-campus-2', 'college-campus-4'],
    logoUrl: 'college-logo-2',
    location: { lat: 17.118, lng: 82.164 },
    mapImage: 'map-placeholder-2',
  },
  {
    id: 15,
    name: 'Indian Institute of Technology Tirupati (IIT Tirupati)',
    city: 'Tirupati',
    district: 'Tirupati',
    description: 'One of the third generation IITs, mentored by IIT Madras. It is rapidly growing and establishing itself as a premier center for science and engineering education.',
    courses: [
        { id: 'cse', name: 'Computer Science and Engineering', department: 'Engineering' },
        { id: 'ee', name: 'Electrical Engineering', department: 'Engineering' },
        { id: 'mech', name: 'Mechanical Engineering', department: 'Engineering' },
        { id: 'civil', name: 'Civil Engineering', department: 'Engineering' },
    ],
    facilities: ['Modern Labs', 'High-Speed Internet', 'Research Park', 'Student Hostels', 'Sports facilities'],
    hostelInfo: 'Well-equipped hostels are available for all students on campus.',
    admissionCutoff: 'Admission is through JEE Advanced exam.',
    rating: 4.8,
    reviews: [
        { id: 1, author: 'Venkatesh Iyer', rating: 5, comment: 'Being an IIT, the brand value is immense. The coding culture is top-notch and faculty are excellent.', date: '2023-10-01' },
    ],
    images: ['college-campus-1', 'college-campus-5'],
    logoUrl: 'college-logo-3',
    location: { lat: 13.629, lng: 79.351 },
    mapImage: 'map-placeholder-3',
  },
  {
    id: 16,
    name: 'IIIT Sri City',
    city: 'Sri City',
    district: 'Tirupati',
    description: 'Indian Institute of Information Technology, Sri City is a research-intensive institute of national importance, focused on Information Technology education and research.',
    courses: [
      { id: 'cse', name: 'Computer Science and Engineering', department: 'Engineering' },
      { id: 'ece', name: 'Electronics and Communication Engineering', department: 'Engineering' },
      { id: 'ai-ds', name: 'Artificial Intelligence and Data Science', department: 'Engineering' }
    ],
    facilities: ['Modern Campus', 'Advanced Labs', 'Start-up centers', 'Robotics lab', 'Library'],
    hostelInfo: 'Fully residential campus with separate hostels for boys and girls.',
    admissionCutoff: 'Based on JEE Main scores, with admission through JoSAA/CSAB counseling.',
    rating: 4.5,
    reviews: [
      { id: 1, author: 'Nithya Menon', rating: 5, comment: 'Excellent curriculum with a focus on current industry trends. Great exposure to research.', date: '2023-09-15' }
    ],
    images: ['college-campus-modern-1', 'college-library-1'],
    logoUrl: 'college-logo-tech',
    location: { lat: 13.568, lng: 80.007 },
    mapImage: 'map-placeholder-4'
  },
  {
    id: 17,
    name: 'JNTU College of Engineering, Anantapur',
    city: 'Anantapur',
    district: 'Anantapur',
    description: 'One of the oldest and most prestigious government engineering colleges in Andhra Pradesh, established in 1946.',
    courses: [
      { id: 'cse', name: 'Computer Science and Engineering', department: 'Engineering' },
      { id: 'eee', name: 'Electrical and Electronics Engineering', department: 'Engineering' },
      { id: 'mech', name: 'Mechanical Engineering', department: 'Engineering' },
      { id: 'civil', name: 'Civil Engineering', department: 'Engineering' }
    ],
    facilities: ['Sprawling Campus', 'Library', 'Workshops', 'Hostels', 'Sports Ground'],
    hostelInfo: 'On-campus hostel facilities are available for both men and women.',
    admissionCutoff: 'Based on AP EAMCET rank. Highly competitive for core branches.',
    rating: 4.4,
    reviews: [
      { id: 1, author: 'Pavan Kalyan', rating: 4, comment: 'Great legacy and experienced faculty. The campus has a lot of history.', date: '2023-06-20' }
    ],
    images: ['college-campus-historic-1', 'college-campus-2'],
    logoUrl: 'college-logo-1',
    location: { lat: 14.654, lng: 77.596 },
    mapImage: 'map-placeholder-1'
  },
  {
    id: 18,
    name: 'Kurnool Medical College',
    city: 'Kurnool',
    district: 'Kurnool',
    description: 'One of the oldest and most renowned medical colleges in Andhra Pradesh, established in 1956.',
    courses: [
      { id: 'mbbs', name: 'MBBS', department: 'Medicine' },
      { id: 'md', name: 'MD (Doctor of Medicine)', department: 'Medicine' },
      { id: 'ms', name: 'MS (Master of Surgery)', department: 'Medicine' }
    ],
    facilities: ['Attached General Hospital', 'Advanced Medical Labs', 'Library', 'Auditorium', 'Hostels'],
    hostelInfo: 'Separate hostel blocks for undergraduate and postgraduate students.',
    admissionCutoff: 'Based on NEET UG and NEET PG ranks.',
    rating: 4.7,
    reviews: [
      { id: 1, author: 'Dr. Anjali', rating: 5, comment: 'Excellent clinical exposure due to the high patient flow in the attached hospital.', date: '2023-02-18' }
    ],
images: ['college-hospital-1', 'college-lab-1'],
    logoUrl: 'college-logo-medical',
    location: { lat: 15.826, lng: 78.037 },
    mapImage: 'map-placeholder-2'
  },
  {
    id: 19,
    name: 'Acharya Nagarjuna University',
    city: 'Guntur',
    district: 'Guntur',
    description: 'A large public university offering a wide range of undergraduate, postgraduate, and doctoral programs across various disciplines.',
    courses: [
      { id: 'mba', name: 'Master of Business Administration', department: 'Management' },
      { id: 'mcom', name: 'Master of Commerce', department: 'Commerce' },
      { id: 'ma-eng', name: 'MA English', department: 'Humanities' },
      { id: 'msc-phy', name: 'M.Sc Physics', department: 'Science' }
    ],
    facilities: ['Central Library', 'Sports Village', 'Health Center', 'Bank', 'Post Office'],
    hostelInfo: 'Extensive hostel facilities for students from various parts of the country.',
    admissionCutoff: 'Based on ANUPGCET for postgraduate courses.',
    rating: 4.0,
    reviews: [
      { id: 1, author: 'Srinivas Rao', rating: 4, comment: 'Vast campus and a good place for higher education. The university has a good reputation.', date: '2023-04-05' }
    ],
    images: ['college-campus-1', 'college-campus-4'],
    logoUrl: 'college-logo-2',
    location: { lat: 16.376, lng: 80.521 },
    mapImage: 'map-placeholder-3'
  }
];

export const allCourses = Array.from(new Set(colleges.flatMap(c => c.courses.map(course => course.department)))).sort();
export const allDistricts = Array.from(new Set(colleges.map(c => c.district))).sort();
